/**
 * CLAUDE.md Generator - Main orchestrator
 * 
 * Coordinates the generation of intelligent CLAUDE.md documentation
 */

import { existsSync, readdirSync } from "fs";
import { writeFile } from "fs/promises";
import { AgentMetadata, ClaudeMdSection, GenerationStrategy } from "./types.js";
import { extractAgentMetadata, parseExistingClaudeMd } from "./parser.js";
import { generateAgentRegistry } from "./generators/registry.js";
import { generateContextFlow } from "./generators/context-flow.js";
import { generateCapabilitiesMatrix } from "./generators/capabilities.js";
import { generateInvocationExamples } from "./generators/examples.js";

/**
 * Generate complete CLAUDE.md content
 */
export async function generateClaudeMd(
  agents: AgentMetadata[],
  existingSections: ClaudeMdSection[] = [],
  strategy: GenerationStrategy = 'create'
): Promise<string> {
  const sections: string[] = [];
  
  // Header
  sections.push('# AI Agent Hub - Orchestration System\n');
  sections.push('*Enhanced with intelligent agent metadata and context flow*\n');
  
  // Agent Registry (only if we have agents with metadata)
  if (agents.length > 0) {
    sections.push(generateAgentRegistry(agents));
  } else {
    sections.push('## Available Agents\n');
    sections.push('*Agents are installed but metadata is being generated.*\n');
  }
  
  // Quick Start (preserve if exists, otherwise generate)
  const existingQuickStart = existingSections.find(s => s.title.includes('Quick Start'));
  if (existingQuickStart && strategy !== 'create') {
    sections.push(`## ${existingQuickStart.title}`);
    sections.push(existingQuickStart.content);
  } else {
    sections.push('## Quick Start\n');
    sections.push('Say: **"Use Studio Coach to [your request]"** to begin orchestrated development.\n');
  }
  
  // Context Flow (only if we have agents with metadata)
  if (agents.length > 0) {
    sections.push(generateContextFlow(agents));
    
    // Capabilities Matrix
    sections.push(generateCapabilitiesMatrix(agents));
    
    // Invocation Examples
    sections.push(generateInvocationExamples(agents));
  }
  
  // MCP Servers (preserve or generate)
  const existingMCP = existingSections.find(s => s.title.includes('MCP Servers'));
  if (existingMCP && strategy !== 'create') {
    sections.push(`## ${existingMCP.title}`);
    sections.push(existingMCP.content);
  } else {
    sections.push('## MCP Servers Available\n');
    sections.push('Your project has been configured with these MCP servers:');
    sections.push('- **Memory** - Persistent conversation context');
    sections.push('- **Sequential Thinking** - Step-by-step reasoning');
    sections.push('- **Context7** - Advanced context management');
    sections.push('- **Playwright** - Browser automation capabilities\n');
  }
  
  // Tips (preserve or generate)
  const existingTips = existingSections.find(s => s.title.includes('Tips'));
  if (existingTips && strategy !== 'create') {
    sections.push(`## ${existingTips.title}`);
    sections.push(existingTips.content);
  } else {
    sections.push('## Tips for Best Results\n');
    sections.push('- Be specific about your requirements');
    sections.push('- Let Studio Coach orchestrate complex tasks');
    sections.push('- Use direct agent calls for focused work');
    sections.push('- Review the context flow to understand agent dependencies');
    sections.push('- Check the capabilities matrix to find the right agent\n');
  }
  
  // Preserve custom sections
  if (strategy === 'merge' || strategy === 'update') {
    const customSections = existingSections.filter(s => s.isCustom);
    if (customSections.length > 0) {
      sections.push('## Custom Documentation\n');
      sections.push('*User-added content preserved below*\n');
      
      for (const custom of customSections) {
        sections.push(`### ${custom.title}`);
        sections.push(custom.content);
      }
    }
  }
  
  // Footer
  sections.push('---');
  sections.push('*Generated by AI Agent Hub - Your AI development team is ready!*');
  
  return sections.join('\n');
}

/**
 * Main function to create or update CLAUDE.md
 */
export async function createOrUpdateClaudeMd(
  agentsDir: string = ".claude/agents",
  outputPath: string = "CLAUDE.md"
): Promise<void> {
  console.log("📝 Generating CLAUDE.md with agent metadata...");
  
  // Determine strategy
  let strategy: GenerationStrategy = 'create';
  let existingSections: ClaudeMdSection[] = [];
  
  if (existsSync(outputPath)) {
    console.log("   Found existing CLAUDE.md, preserving custom content...");
    strategy = 'merge';
    existingSections = await parseExistingClaudeMd(outputPath);
  }
  
  // Extract agent metadata
  const agents = await extractAgentMetadata(agentsDir);
  
  // Check for agents without metadata
  const allAgentFiles = existsSync(agentsDir) 
    ? readdirSync(agentsDir).filter(f => f.endsWith('.md'))
    : [];
  
  const agentsWithoutMetadata = allAgentFiles.length - agents.length;
  
  if (agents.length === 0 && allAgentFiles.length === 0) {
    console.warn("⚠️  No agents found in", agentsDir);
    return;
  }
  
  if (agents.length > 0) {
    console.log(`   Found ${agents.length} agents with metadata`);
  }
  
  if (agentsWithoutMetadata > 0) {
    console.log(`   Found ${agentsWithoutMetadata} agent(s) without metadata (will be listed separately)`);
  }
  
  // Generate content
  const content = await generateClaudeMd(agents, existingSections, strategy);
  
  // Write file
  await writeFile(outputPath, content);
  
  if (strategy === 'create') {
    console.log("✅ Created CLAUDE.md with rich agent documentation");
  } else {
    console.log("✅ Updated CLAUDE.md while preserving custom content");
  }
}